name: Auto Logger AQI & Weather Pekanbaru

on:
  schedule:
    # Pukul 19:00 s.d 23:00 WIB (12:00 - 16:00 UTC) setiap 40 menit
    - cron: '0,40 12,13,14,15,16 * * *'
    # Pukul 00:00 s.d 08:00 WIB (17:00 - 01:00 UTC) setiap 40 menit
    - cron: '0,40 17,18,19,20,21,22,23,0,1,2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-logger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pandas

      - name: Run Logger Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python logger.py

      - name: Commit and Push Dataset Changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Auto-update air quality & weather dataset log (Night shift)" || exit 0
          git push
