name: Jalankan Scraper Penerbangan PKU

on:
  schedule:
    - cron: '0 17 * * *' # Otomatis berjalan setiap hari jam 00:00 WIB (17:00 UTC)
  workflow_dispatch: # Memunculkan tombol jalankan manual

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Ambil Kode dari Repositori
      uses: actions/checkout@v4

    - name: Siapkan Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instal Pustaka Pendukung
      run: pip install pandas requests

    - name: Eksekusi Kode Scraper
      env:
        AIRLABS_API_KEY: ${{ secrets.AIRLABS_API_KEY }} 
      run: python flight_logger.py

    - name: Simpan File CSV Hasil Olahan ke GitHub (Sistem Proteksi Error)
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        
        # Mengecek apakah file CSV berhasil dibuat oleh scraper.py
        if [ -f dataset_analisis_penerbangan_pku.csv ]; then
          echo "File CSV ditemukan! Memulai proses push ke repository..."
          git add dataset_analisis_penerbangan_pku.csv
          git commit -m "Update dataset otomatis - $(date +'%Y-%m-%d')" || exit 0
          git push
        else
          echo "WARNING: File dataset_analisis_penerbangan_pku.csv tidak ditemukan!"
          echo "Artinya skrip Python gagal mendapatkan data dari AirLabs (Cek log di atas)."
          exit 1
        fi
